### ISSUE TITLE
Can´t start the engine

### ISSUE THREAD

**Issue by echtAbgezockt** [LielXD/xd_locksystem#2]
Hey, i cant start the Engine but i have the keys and can lock and unlock the Vehicle

**Comment by LielXD** [comment]
You have any other locksystem script?

**Comment by echtAbgezockt** [comment]
no

**Comment by LielXD** [comment]
releasing soon a complete rewrite script v2.

**Comment by LielXD** [comment]
releasing soon a complete rewrite script v2.
