### ISSUE TITLE
Keys Not Working

### ISSUE THREAD

**Issue by dexidexa** [LielXD/xd_locksystem#5]
Hello. When a player buys a vehicle at the dealership or when he takes it out of the garage, he does not give him the keys and always needs to hotwire it, is there an export to give the keys or something similar, I attach the code of the dealership where the export should go

```
function SetVehicleOwner(plate)
    if not Config.UseKeySystem then return end

    if Framework.name == 'es_extended' then
		-- export here
            
    elseif Framework.name == 'qb-core' then
        TriggerEvent("vehiclekeys:client:SetOwner", plate)
    end
end
```

**Comment by LielXD** [comment]
If you will read the readme or the resource page in cfx.re you will clearly see i mentioned the export please have a look again and read all the instructions before reporting an issue.
