### ISSUE TITLE
bad argument #1 to 'lower' (string expected, got boolean)

### ISSUE THREAD

**Issue by Milosh94** [LielXD/xd_locksystem#6]
HI,
I just put this script on my server.
I get this error in Console and I don't know how to resolve it.
Can you help me?

![Locksystemerror](https://github.com/LielXD/xd_locksystem/assets/28486937/e8e52ba8-351d-48a7-9924-8e955544e213)

**Comment by LielXD** [comment]
you probably made a change to Config.Framework let me see your config file.

**Comment by Milosh94** [comment]
> probabilmente hai apportato una modifica a Config.Framework, fammi vedere il tuo file di configurazione.

I managed to resolve I had mistakenly written true instead of ESX.

Is it possible to play the lockpick minigame only if you have the lockpick in your inventory?

**Comment by LielXD** [comment]
and if you don't have?
they will not have any access to vehicles.
